mysql:
 host: 127.0.0.1
 port: 3306
 user: root
 pass: yeungan
 database: minefs
#Sửa thành true nếu plugin này cài ở lobby hoặc chỉ chạy một server duy nhất không dùng Bungeecord, khi đó plugin sẽ log IP của player
log: false